version: '3'

services:
  backend:
    image: igs-roti-backend
    build: ./backend
    env_file: ./backend/.env
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/igs-roti-backend
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload

  frontend:
    image: igs-roti-frontend
    build:
      context: ./frontend
      target: 'dev'
    ports:
      - '8080:8080'
    volumes:
      - ./frontend:/igs-roti-frontend
      - /igs-roti-frontend/node_modules
    command: npm run serve
