name: Dependabot auto merge

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
        working-directory: ./frontend
      - name: Build package
        run: npm run build
        working-directory: ./frontend

  auto-merge:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        uses: fastify/github-action-merge-dependabot@v2.1.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
